/**
 * hermes-home-seed.ts
 *
 * Idempotent seed-once migration for existing Hermes CLI users launching
 * packaged Atum for the first time.
 *
 * The packaged engine home (app.getPath('userData')/hermes-home) starts
 * empty. A user who already configured the CLI would otherwise face a blank
 * provider setup even though a working config.yaml / .env / auth.json exists
 * one directory over. This module COPIES the minimum static/provider
 * selection files into the Atum home — once, atomically, and never again.
 *
 * Boundaries (hard rules):
 *   - COPY ONLY the allowlist: config.yaml, .env, auth.json, SOUL.md, and the
 *     skins/ directory when present. These are the static files current
 *     functionality needs; everything else is regenerated by the engine.
 *   - NEVER copy sessions, profiles, memory, plugins, cron, cache, logs,
 *     hermes-agent (source checkout), node, locks, or the shared/ refresh-token
 *     store. The allowlist is the enforcement mechanism: anything not listed
 *     is not copied, by construction.
 *   - NEVER move, delete, or re-sync the source. The CLI home stays the CLI's.
 *     This is a one-way, one-time copy; later edits on either side diverge by
 *     design (product isolation).
 *   - NEVER follow symlinks out of the source: a symlinked config.yaml would
 *     make the Atum backend write through into the CLI home. Symlinked
 *     entries are skipped and reported.
 *   - Only runs when the Atum home is ABSENT. An existing home — seeded,
 *     hand-created, or half-created — is left alone. Honest marker: the
 *     marker file is written into the staging directory BEFORE the atomic
 *     rename, so a present home implies a completed seed; a crash mid-copy
 *     leaves only a .seed-in-progress directory that the next launch cleans
 *     up and retries.
 *
 * Pure + DI-testable: all filesystem access arrives through `deps`, so the
 * tests run against an in-memory fake. main.ts wires the real fs bindings.
 */

import path from 'node:path'

// Static provider/setup selection files. Secrets stay on the same machine,
// owned by the same user; the copy is what lets the packaged engine reuse the
// provider the user already chose instead of resetting them to onboarding.
const SEED_FILE_NAMES = Object.freeze(['config.yaml', '.env', 'auth.json', 'SOUL.md'])
const SEED_DIRECTORY_NAMES = Object.freeze(['skins'])
const SEED_MARKER_NAME = '.atum-home-seed.json'
const SEED_STAGING_SUFFIX = '.seed-in-progress'
const SEED_MARKER_SCHEMA_VERSION = 1

interface SeedDeps {
  exists(candidate: string): boolean
  isDirectory(candidate: string): boolean
  isSymbolicLink(candidate: string): boolean
  copyEntry(source: string, target: string): void
  mkdirp(target: string): void
  rename(source: string, target: string): void
  remove(target: string): void
  writeFile(target: string, contents: string): void
  now(): string
}

/**
 * The seedable entries actually present under `sourceHome`, in allowlist
 * order. Symlinks are excluded — copying through one would alias the Atum
 * home back into the CLI home and break isolation on the first write.
 */
function collectSeedEntries(sourceHome, { exists, isDirectory, isSymbolicLink }: Partial<SeedDeps> = {}) {
  const entries: Array<{ kind: string; name: string; source: string }> = []
  const skipped: string[] = []

  const consider = (name, kind) => {
    const source = path.join(sourceHome, name)

    if (!exists(source)) {
      return
    }

    if (isSymbolicLink(source)) {
      skipped.push(name)

      return
    }

    if (kind === 'file' && isDirectory(source)) {
      return
    }

    if (kind === 'directory' && !isDirectory(source)) {
      return
    }

    entries.push({ kind, name, source })
  }

  for (const name of SEED_FILE_NAMES) {
    consider(name, 'file')
  }

  for (const name of SEED_DIRECTORY_NAMES) {
    consider(name, 'directory')
  }

  return { entries, skipped }
}

/**
 * Run the seed-once migration. Returns a small result record describing what
 * happened; never throws for expected states (absent source, existing
 * target). Filesystem failures from the injected deps propagate — the main
 * process catches and logs them, and a failed seed must never block a boot.
 */
function seedHermesHomeOnce({
  sourceHome,
  targetHome,
  deps
}: {
  sourceHome: string
  targetHome: string
  deps: SeedDeps
}) {
  const { exists, isDirectory, isSymbolicLink, copyEntry, mkdirp, rename, remove, writeFile, now } = deps

  if (!sourceHome || !targetHome || path.resolve(sourceHome) === path.resolve(targetHome)) {
    return { status: 'skipped', reason: 'same-home', entries: [] }
  }

  if (isDirectory(targetHome) || exists(targetHome)) {
    return { status: 'skipped', reason: 'target-exists', entries: [] }
  }

  if (!isDirectory(sourceHome)) {
    return { status: 'skipped', reason: 'source-absent', entries: [] }
  }

  const { entries, skipped } = collectSeedEntries(sourceHome, { exists, isDirectory, isSymbolicLink })

  if (entries.length === 0) {
    return { status: 'skipped', reason: 'nothing-to-seed', entries: [], skipped }
  }

  const staging = `${targetHome}${SEED_STAGING_SUFFIX}`

  // Crash residue from a previous interrupted attempt: the rename never
  // happened, so the staging dir is the only trace. Clear it and redo.
  if (exists(staging)) {
    remove(staging)
  }

  mkdirp(staging)

  for (const entry of entries) {
    copyEntry(entry.source, path.join(staging, entry.name))
  }

  // Marker lands in staging BEFORE the rename, so a completed rename always
  // implies a completed seed — the marker can never claim a copy that didn't
  // finish. It records names only, never file contents.
  writeFile(
    path.join(staging, SEED_MARKER_NAME),
    JSON.stringify(
      {
        schemaVersion: SEED_MARKER_SCHEMA_VERSION,
        seededAt: now(),
        sourceHome,
        entries: entries.map(entry => entry.name),
        skippedSymlinks: skipped
      },
      null,
      2
    ) + '\n'
  )

  // Re-check before the rename: another window may have created the home
  // while we copied. Losing the race is fine — their home wins, ours goes.
  if (exists(targetHome)) {
    remove(staging)

    return { status: 'skipped', reason: 'target-appeared', entries: [] }
  }

  rename(staging, targetHome)

  return { status: 'seeded', reason: 'seeded', entries: entries.map(entry => entry.name), skipped }
}

/**
 * Should the packaged app attempt a seed at all? Sandboxed test runs
 * (HERMES_DESKTOP_USER_DATA_DIR) must stay hermetic — seeding would pull the
 * developer's real CLI config into the throwaway home.
 */
function shouldSeedPackagedHome({ isPackaged, env = process.env }: any = {}) {
  if (!isPackaged) {
    return false
  }

  return !String(env?.HERMES_DESKTOP_USER_DATA_DIR || '').trim()
}

export {
  collectSeedEntries,
  SEED_DIRECTORY_NAMES,
  SEED_FILE_NAMES,
  SEED_MARKER_NAME,
  SEED_MARKER_SCHEMA_VERSION,
  SEED_STAGING_SUFFIX,
  seedHermesHomeOnce,
  shouldSeedPackagedHome
}
